---
- name: stop tomcat
  service:
    name: tomcat7
    state: stopped

- name: add the fedora group
  group:
    name: '{{ fedora_group }}'

- name: create the fedora user
  user:
    name: '{{ fedora_user }}'
    group: '{{ fedora_group }}'
    home: '{{ fedora_user_home }}'

- name: create fedora data dir
  file:
    path: '{{ fedora_data_dir }}'
    owner: '{{ fedora_user }}'
    group: '{{ fedora_group }}'
    state: directory

- name: copy patched fedora war into place
  copy:
    src: "{{ local_files_dir }}/fcrepo-webapp-4.5.1.war"
    dest: '{{ fedora_app_dir }}/fedora.war'

- name: add fedora and java config options to tomcat
  lineinfile:
    dest: /etc/default/tomcat7
    line: JAVA_OPTS='-Dfcrepo.home={{ fedora_data_dir }} -Djava.awt.headless=true -Dfile.encoding=UTF-8 -server {{ fedora_java_vm_opts }}'
    regexp: "^JAVA_OPTS=.*"
    state: present

- name: start tomcat
  service:
    name: tomcat7
    state: started
